[package]
name = "proof-of-rent"
version = "0.1.0"
description = "Proof of Rent: tenant passports and deposit escrow"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "proof_of_rent"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "1.1.2"
anchor-spl = "1.1.2"

[dev-dependencies]
litesvm = "0.10.0"
solana-sdk = "3"
spl-token-interface = "2.0"
solana-program-pack = "3"
spl-associated-token-account-interface = "2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
